package test;

import java.util.Arrays;
import java.util.Scanner;

public class TestCatch {
    public static void main(String[] args) {
        //try ---> блок который обрабатывает потенциальное исключение
        // catch ---> блок который обрабатывает (перехватывает) исключения

        /*
        Scanner scan = new Scanner(System.in);
        System.out.println("Введите первое число");
        int n1 = scan.nextInt();
        System.out.println("Введите второе число");
        int n2 = scan.nextInt();


        try {
            System.out.println("Результат " + n1 / n2);
        } catch (ArithmeticException exception) {
            System.out.println("Число " + n1 + " нельзя поделить на " + n2 + "!");
        }
        finally {
            System.out.println("Обработка выполнена");
        }
        */




    /*    int[] array = new int[5];
        array[0] = 1;
        array[1] = 2;
        array[2] = 3;
        array[3] = 4;
        array[4] = 5;

        try {
            array[5] = 6;
        } catch (Exception exception) {
            System.out.println("Выход за пределы массива");
        }*/


      /*  for (int c = 0; c < array.length; c++) {
            System.out.println(array[c]);
        }*/
    }
}
